"""Osservatore semantico annuale di PostiPerfetti — incrementi I1–I10.

I10 aggiunge audit finale, riproducibilità interprocesso e verifica del contratto R0.1.
"""

from .aggregati import (
    ErroreAggregazione,
    costruisci_annata_canonica,
    costruisci_cronologia_adiacenze,
    costruisci_ricerca_annuale,
    costruisci_riepilogo_annuale,
    costruisci_riepiloghi_studenti,
    costruisci_serie_mensile,
)
from .genere_misto import (
    ErroreGenereMisto,
    arricchisci_annata_genere_misto,
    calcola_massimo_ammissibile,
    calcola_massimo_geometrico,
    costruisci_analisi_genere_misto,
)
from .adattatori_comuni import (
    BloccoFisico, ErroreAdattatore, MeseAdattato, RelazioneAdattata,
)
from .adattatore_coppie import adatta_mese_coppie
from .adattatore_terzetti import adatta_mese_terzetti
from .cronologia import (
    ErroreCronologia, EsitoCronologiaI4, costruisci_cronologia, osserva_esito_c1,
)
from .ambiente import (
    AmbienteRunIsolato,
    AmbientiAppaiati,
    ErroreAmbienteIsolato,
    ErroreClassiAppaiate,
    EsitoClassiAppaiate,
    carica_e_valida_coppia_classi,
    prepara_ambiente_run,
    prepara_ambienti_appaiati,
    valida_dati_classi_appaiate,
    verifica_sorgente_immutata,
)
from .esecuzione_c1 import (
    ErroreEsecuzioneC1,
    EsitoC1,
    esegui_c1,
    esegui_c1_coppie,
    esegui_c1_terzetti,
)
from .riordino import (
    ErroreRiordinoC1,
    riordina_coppie_con_traccia,
    riordina_terzetti_con_traccia,
)
from .identita import (
    chiave_adiacenza,
    crea_confronto_id,
    crea_event_id,
    crea_group_id,
    crea_identificatore,
    crea_pair_id,
    crea_run_id,
)
from .modelli import (
    AnalisiGenereAnnuale,
    AnalisiGenereMese,
    AnnataCanonica,
    EsitoOttimoMisto,
    GruppoNonPienamenteMisto,
    CronologiaAdiacenza,
    CanaleRotazione,
    CondizioneRun,
    EventoAdiacenza,
    FasciaRipetizione,
    FunzioneGruppo,
    GruppoCanonico,
    MeseCanonico,
    Modalita,
    OrigineUltimoUso,
    ParametriAula,
    ParametriRicerca,
    PuntoSerieMensile,
    ProtocolloRaccolta,
    RiepilogoAnnuale,
    RiepilogoMensile,
    RiepilogoStudente,
    RuoloAdiacenza,
    SnapshotRotazioni,
    SpecificaCoppiaCorpus,
    SpecificaRun,
    StatoRun,
    TipoGruppo,
    TracciaMese,
    UltimoUso,
    VersioniOutput,
    VoceRotazione,
    VoceVicinoFisso,
)
from .protocollo import ErroreProtocollo, carica_protocollo, valida_protocollo
from .serializzazione import (
    firma_file_sha256,
    firma_json_sha256,
    leggi_json,
    serializza_json,
    scrivi_json_atomico,
    scrivi_testo_atomico,
)

from .validazione import (
    ErroreValidazioneOutput,
    richiedi_annata_valida,
    valida_annata,
    valida_dati_annata,
)
from .rendering_markdown import (
    ErroreRenderingMarkdown,
    rendi_rapporto_markdown,
    scrivi_rapporto_markdown,
)
from .output_run import (
    ErrorePubblicazioneRun,
    EsitoPubblicazioneRun,
    RecordFallimentoRun,
    pubblica_output_run,
    record_fallimento_da_eccezione,
    scrivi_fallimento_run,
)
from .confronto_appaiato import (
    ConfrontoAppaiato,
    ErroreConfrontoAppaiato,
    EsitoPubblicazioneConfronto,
    EsitoValidazioneConfronto,
    ProblemaAppaiamento,
    costruisci_confronto_appaiato,
    pubblica_confronto_appaiato,
    rendi_confronto_markdown,
    valida_dati_confronto,
)

from .raccolta import (
    ErroreRaccolta,
    EsitoEsecuzioneMatrice,
    EsitoPubblicazioneRaccolta,
    esegui_matrice_protocollo,
    pubblica_raccolta_da_output,
    valida_raccolta,
    verifica_manifesto,
)


from .audit_finale import (
    ControlloAudit,
    ErroreAuditFinale,
    audita_raccolta,
    confronta_firme_produzione,
    confronta_raccolte_riproducibili,
    firma_albero_produzione,
    pubblica_audit_finale,
    rendi_audit_markdown,
)

from .snapshot import (
    ErroreSnapshot,
    crea_snapshot_rotazioni,
    crea_stato_iniziale_id,
    firma_snapshot,
    scrivi_snapshot,
    snapshot_da_file_configurazione,
    verifica_snapshot,
)

__all__ = [
    "ConfrontoAppaiato",
    "ErroreConfrontoAppaiato",
    "EsitoPubblicazioneConfronto",
    "EsitoValidazioneConfronto",
    "ProblemaAppaiamento",
    "costruisci_confronto_appaiato",
    "pubblica_confronto_appaiato",
    "rendi_confronto_markdown",
    "valida_dati_confronto",
    "ErroreAggregazione",
    "ErroreGenereMisto",
    "arricchisci_annata_genere_misto",
    "calcola_massimo_ammissibile",
    "calcola_massimo_geometrico",
    "costruisci_analisi_genere_misto",
    "costruisci_annata_canonica",
    "costruisci_cronologia_adiacenze",
    "costruisci_ricerca_annuale",
    "costruisci_riepilogo_annuale",
    "costruisci_riepiloghi_studenti",
    "costruisci_serie_mensile",
    "BloccoFisico",
    "ErroreAdattatore",
    "ErroreCronologia",
    "EsitoCronologiaI4",
    "MeseAdattato",
    "RelazioneAdattata",
    "adatta_mese_coppie",
    "adatta_mese_terzetti",
    "costruisci_cronologia",
    "osserva_esito_c1",
    "AmbienteRunIsolato",
    "AmbientiAppaiati",
    "AnalisiGenereAnnuale",
    "AnalisiGenereMese",
    "AnnataCanonica",
    "EsitoOttimoMisto",
    "GruppoNonPienamenteMisto",
    "CanaleRotazione",
    "CondizioneRun",
    "CronologiaAdiacenza",
    "ErroreAmbienteIsolato",
    "ErroreClassiAppaiate",
    "ErroreEsecuzioneC1",
    "ErroreRiordinoC1",
    "ErroreProtocollo",
    "ErroreSnapshot",
    "EsitoClassiAppaiate",
    "EsitoC1",
    "EventoAdiacenza",
    "FasciaRipetizione",
    "FunzioneGruppo",
    "GruppoCanonico",
    "MeseCanonico",
    "Modalita",
    "OrigineUltimoUso",
    "ParametriAula",
    "ParametriRicerca",
    "PuntoSerieMensile",
    "ProtocolloRaccolta",
    "RiepilogoAnnuale",
    "RiepilogoMensile",
    "RiepilogoStudente",
    "RuoloAdiacenza",
    "SnapshotRotazioni",
    "SpecificaCoppiaCorpus",
    "SpecificaRun",
    "StatoRun",
    "TipoGruppo",
    "TracciaMese",
    "UltimoUso",
    "VersioniOutput",
    "VoceRotazione",
    "VoceVicinoFisso",
    "carica_e_valida_coppia_classi",
    "carica_protocollo",
    "chiave_adiacenza",
    "crea_confronto_id",
    "crea_event_id",
    "crea_group_id",
    "crea_identificatore",
    "crea_pair_id",
    "crea_run_id",
    "crea_snapshot_rotazioni",
    "crea_stato_iniziale_id",
    "firma_file_sha256",
    "firma_json_sha256",
    "firma_snapshot",
    "esegui_c1",
    "esegui_c1_coppie",
    "esegui_c1_terzetti",
    "leggi_json",
    "prepara_ambiente_run",
    "prepara_ambienti_appaiati",
    "riordina_coppie_con_traccia",
    "riordina_terzetti_con_traccia",
    "scrivi_json_atomico",
    "scrivi_snapshot",
    "serializza_json",
    "snapshot_da_file_configurazione",
    "valida_dati_classi_appaiate",
    "valida_protocollo",
    "verifica_snapshot",
    "ErroreValidazioneOutput",
    "ErroreRenderingMarkdown",
    "ErrorePubblicazioneRun",
    "EsitoPubblicazioneRun",
    "RecordFallimentoRun",
    "valida_annata",
    "valida_dati_annata",
    "richiedi_annata_valida",
    "rendi_rapporto_markdown",
    "scrivi_rapporto_markdown",
    "pubblica_output_run",
    "record_fallimento_da_eccezione",
    "scrivi_fallimento_run",
    "scrivi_testo_atomico",
    "verifica_sorgente_immutata",
    "ErroreRaccolta",
    "EsitoEsecuzioneMatrice",
    "EsitoPubblicazioneRaccolta",
    "esegui_matrice_protocollo",
    "pubblica_raccolta_da_output",
    "valida_raccolta",
    "verifica_manifesto",
    "ControlloAudit", "ErroreAuditFinale", "audita_raccolta",
    "confronta_firme_produzione", "confronta_raccolte_riproducibili",
    "firma_albero_produzione", "pubblica_audit_finale",
    "rendi_audit_markdown",
]

__version__ = "1.0.0"
